export function getCuratedTracks(emotion: string) {
  const tracksByEmotion = {
    happy: [
      {
        name: "Happy",
        artists: [{ name: "Pharrell Williams" }],
        duration: "3:53",
        url: "https://open.spotify.com/track/60nZcImufyMA1MKQY3dcCH",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "1.2B",
      },
      {
        name: "Good as Hell",
        artists: [{ name: "Lizzo" }],
        duration: "2:39",
        url: "https://open.spotify.com/track/1PckUlxKqWQs3RlWXVBLw3",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "800M",
      },
      {
        name: "Can't Stop the Feeling!",
        artists: [{ name: "Justin Timberlake" }],
        duration: "3:56",
        url: "https://open.spotify.com/track/4bHsxqR3GMrXTxEPLuK5ue",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "1.5B",
      },
      {
        name: "Walking on Sunshine",
        artists: [{ name: "Katrina and the Waves" }],
        duration: "3:58",
        url: "https://open.spotify.com/track/05wIrZSwuaVWhcv5FfqeH0",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "500M",
      },
    ],
    sad: [
      {
        name: "Someone Like You",
        artists: [{ name: "Adele" }],
        duration: "4:45",
        url: "https://open.spotify.com/track/4sPmO7WMQUAf45kwMOtONw",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "2B",
      },
      {
        name: "Mad World",
        artists: [{ name: "Gary Jules" }],
        duration: "3:07",
        url: "https://open.spotify.com/track/3JOVTQ5h8HGFnDdp4VT3MP",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "300M",
      },
      {
        name: "Hurt",
        artists: [{ name: "Johnny Cash" }],
        duration: "3:38",
        url: "https://open.spotify.com/track/4gMgiXfqyzZLMhsksGmbQV",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "400M",
      },
      {
        name: "Black",
        artists: [{ name: "Pearl Jam" }],
        duration: "5:43",
        url: "https://open.spotify.com/track/2Foc5Q5nqNiosCNqttzHof",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "200M",
      },
    ],
    energized: [
      {
        name: "Eye of the Tiger",
        artists: [{ name: "Survivor" }],
        duration: "4:04",
        url: "https://open.spotify.com/track/2KH16WveTQWT6KOG9Rg6e2",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "1B",
      },
      {
        name: "Pump It",
        artists: [{ name: "The Black Eyed Peas" }],
        duration: "3:33",
        url: "https://open.spotify.com/track/3URWiTy5wvKhWWdJYWqBsm",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "800M",
      },
      {
        name: "Thunder",
        artists: [{ name: "Imagine Dragons" }],
        duration: "3:07",
        url: "https://open.spotify.com/track/1zB4vmk8tFRmM9UULNzbLB",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "2.5B",
      },
      {
        name: "Stronger",
        artists: [{ name: "Kelly Clarkson" }],
        duration: "3:42",
        url: "https://open.spotify.com/track/0jOXKZQBLsJXGBuGNxqnQs",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "600M",
      },
    ],
    peaceful: [
      {
        name: "Weightless",
        artists: [{ name: "Marconi Union" }],
        duration: "8:08",
        url: "https://open.spotify.com/track/6p0q6tSchxVeqnKIVY0Ekt",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "50M",
      },
      {
        name: "Clair de Lune",
        artists: [{ name: "Claude Debussy" }],
        duration: "5:20",
        url: "https://open.spotify.com/track/4Tr0oGOIbINNEmWKBEBNEW",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "100M",
      },
      {
        name: "River",
        artists: [{ name: "Joni Mitchell" }],
        duration: "4:00",
        url: "https://open.spotify.com/track/3SdTKo2uVsxFblQjpScoHy",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "150M",
      },
      {
        name: "Mad About You",
        artists: [{ name: "Sting" }],
        duration: "3:56",
        url: "https://open.spotify.com/track/1Je1IMUlBXcx1Fz0WE7oPT",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "80M",
      },
    ],
    creative: [
      {
        name: "Bohemian Rhapsody",
        artists: [{ name: "Queen" }],
        duration: "5:55",
        url: "https://open.spotify.com/track/4u7EnebtmKWzUH433cf5Qv",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "1.8B",
      },
      {
        name: "Imagine",
        artists: [{ name: "John Lennon" }],
        duration: "3:07",
        url: "https://open.spotify.com/track/7pKfPomDEeI4TPT6EOYjn9",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "1.5B",
      },
      {
        name: "Paint It Black",
        artists: [{ name: "The Rolling Stones" }],
        duration: "3:22",
        url: "https://open.spotify.com/track/63T7DJ1AFDD6Bn8VzG6JE8",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "900M",
      },
    ],
    romantic: [
      {
        name: "Perfect",
        artists: [{ name: "Ed Sheeran" }],
        duration: "4:23",
        url: "https://open.spotify.com/track/0tgVpDi06FyKpA1z0VMD4v",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "3.2B",
      },
      {
        name: "All of Me",
        artists: [{ name: "John Legend" }],
        duration: "4:29",
        url: "https://open.spotify.com/track/3U4isOIWM3VvDubwSI3y7a",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "2.8B",
      },
      {
        name: "Thinking Out Loud",
        artists: [{ name: "Ed Sheeran" }],
        duration: "4:41",
        url: "https://open.spotify.com/track/1KiHdWMbzjjOgzAhBrFcKF",
        image: "/placeholder.svg?height=80&width=80",
        playcount: "2.9B",
      },
    ],
  }

  return tracksByEmotion[emotion] || tracksByEmotion.happy
}
